# Docker compose file for the nodejs application

version: '3.9'

services:
  nodejs:
    build: .
    image: ameyajain25/nodejs-ec2-ci-cd:latest
    container_name: nodejs-ec2
    ports:
      - 4001:3000
    volumes:
      - .:/app
