# Github CI/CD Workflow for NodeJS Docker Image Build and Push to Docker Hub with compose

name: Docker NodeJS

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Docker login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin

      - name: Build the Docker image
        run: docker compose build

      - name: Tag the Docker image
        run: docker tag my-nodejs-app:latest ${{ secrets.DOCKER_USERNAME }}/nodejs-ec2-ci-cd:latest

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push the Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/nodejs-ec2-ci-cd:latest

  start:
    runs-on: self-hosted
    needs: build
    steps:
      - uses: actions/checkout@v3

      # - name: Docker login
      #   env:
      #     DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      #     DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      #   run: |
      #     echo $DOCKER_PASSWORD | sudo docker login --username $DOCKER_USERNAME --password-stdin

      - name: Pull the Docker image
        run: sudo docker pull ${{ secrets.DOCKER_USERNAME }}/nodejs-ec2-ci-cd:latest

      - name: Tagging new docker image as my-nodejs-app
        run: sudo docker tag ${{ secrets.DOCKER_USERNAME }}/nodejs-ec2-ci-cd:latest my-nodejs-app:latest

      - name: Run the Docker image with compose
        run: sudo docker compose up -d

      - name: Check the Docker image
        run: sudo docker ps
